// File automatically generated by swift-bridge.
#include <stdint.h>
void* __swift_bridge__$ext_generate_extrinsic_proof(void* call, void* signed_extras, void* additional_signed, void* metadata, uint32_t spec_version, void* spec_name, uint16_t base58_prefix, uint8_t decimals, void* token_symbol);
void* __swift_bridge__$ext_generate_metadata_digest(void* metadata, uint32_t spec_version, void* spec_name, uint16_t base58_prefix, uint8_t decimals, void* token_symbol);


